name: Commit Phase

on:
  push:
    branches:
      - main # or specify your desired branch
      - refactor/ci

jobs:
  build-test-lint-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.16

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test (core unit tests)
        run: npm run test:unit

      - name: Lint
        run: npm run lint

      - name: Archive Frontend
        id: frontend-build
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build-${{ github.run_number }}
          path: ./packages/frontend/dist
          # Customize Artifact Retention Period
          retention-days: 2

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [build-test-lint-archive]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download frontend build artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-build-${{ github.run_number }}
          path: ./frontend-build
        
      - name: Deploy to Frontend Staging on Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=frontend-build --alias=staging 
        
      - name: Trigger Render Deployment Webhook 
        run: |
          curl -X GET https://api.render.com/deploy/srv-cijkadtph6euh7k6e49g?key=DXxdTMsFGOQ

      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_API_KEY }}
          github-token: ${{ secrets.REPO_TOKEN }}
          service-id: srv-cijkadtph6euh7k6e49g
          retries: 20
          wait: 16000
          sleep: 30000
