name: Commit Phase

on:
  push:
    branches:
      - main # or specify your desired branch

jobs:
  build-test-lint-archive:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.16

      - name: Install Globals
        run: npm install -g typescript @types/node rimraf cross-env

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Test (core unit tests)
        run: npm run test:unit

      - name: Lint
        run: npm run lint

      - name: Create frontend build artifact
        id: frontend-build
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build-latest
          path: ./packages/frontend/dist
          # Customize Artifact Retention Period
          retention-days: 2

  trigger-staging:
    runs-on: ubuntu-latest
    needs: [build-test-lint]

    steps:
      - name: Trigger staging workflow
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          script: |
            const response = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file: 'staging.yml'
            });
            console.log(response);